---
abstract: "Handle passing of status (success and error)\nmessages between screens of a web application."
author:
  - 'Kennedy Clark <hkclark@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-StatusMessage
requires:
  Catalyst: 5.80000
  Sub::Name: 0
  strictures: 0
version: 1.001000
